# Generated by Django 4.0.4 on 2022-04-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idadmin', models.AutoField(db_column='IdAdmin', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Nom', max_length=20, null=True)),
                ('prenom', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Prenom', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Email', max_length=50, null=True)),
                ('role', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Role', max_length=30, null=True)),
                ('password', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Password', max_length=12, null=True)),
            ],
            options={
                'db_table': 'Admin',
                'managed': False,
            },
        ),
    ]
