# Generated by Django 4.0.4 on 2022-04-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('idconge', models.AutoField(db_column='IdConge', primary_key=True, serialize=False)),
                ('type_conge', models.CharField(blank=True, db_collation='French_CI_AS', max_length=30, null=True)),
                ('datedebut', models.DateTimeField(blank=True, db_column='dateDebut', null=True)),
                ('dateretour', models.DateTimeField(blank=True, db_column='dateRetour', null=True)),
                ('nbjour', models.IntegerField(blank=True, db_column='nbJour', null=True)),
            ],
            options={
                'db_table': 'CongeSet',
                'managed': False,
            },
        ),
    ]
