# Generated by Django 4.0.4 on 2022-04-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionConge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conge',
            table='Conge',
        ),
    ]
