# Generated by Django 4.0.4 on 2022-05-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionConge', '0002_alter_conge_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateElimine',
            fields=[
                ('ideateelimine', models.AutoField(db_column='IdDateElimine', primary_key=True, serialize=False)),
                ('motif', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Motif', max_length=50, null=True)),
                ('dateelimine', models.DateTimeField(blank=True, db_column='DateElimine', null=True)),
            ],
            options={
                'db_table': 'DateElimine',
                'managed': False,
            },
        ),
    ]
