# Generated by Django 4.0.4 on 2022-06-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionConge', '0003_dateelimine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conge',
            options={'managed': False, 'verbose_name': 'الرخصة', 'verbose_name_plural': 'الرخص'},
        ),
        migrations.AlterModelOptions(
            name='dateelimine',
            options={'managed': False, 'verbose_name': 'العطلة', 'verbose_name_plural': 'العطل'},
        ),
    ]
