# Generated by Django 4.0.4 on 2022-06-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnexeStage',
            fields=[
                ('idannexestage', models.AutoField(db_column='IdAnnexeStage', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'AnnexeStage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CaidatStage',
            fields=[
                ('idcaidatstage', models.AutoField(db_column='IdAnnexeStage', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CaidatStage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PashalikStage',
            fields=[
                ('idpashalikstage', models.AutoField(db_column='IdPashalikStage', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PashalikStage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceStage',
            fields=[
                ('idservicestage', models.AutoField(db_column='IdServiceStage', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ServiceStage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('idstage', models.AutoField(db_column='IdStage', primary_key=True, serialize=False)),
                ('nomstagiairear', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NomStagiaireAr', max_length=20, null=True)),
                ('prenomstagiairear', models.CharField(blank=True, db_collation='French_CI_AS', db_column='PrenomStagiaireAr', max_length=20, null=True)),
                ('nomstagiairefr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NomStagiaireFr', max_length=20, null=True)),
                ('prenomstagiairefr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='PrenomStagiaireFr', max_length=20, null=True)),
                ('cin', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Cin', max_length=20, null=True)),
                ('sexe', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Sexe', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Email', max_length=40, null=True)),
                ('tele', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Tele', max_length=20, null=True)),
                ('datedebutstage', models.DateTimeField(blank=True, db_column='DateDebutStage', null=True)),
                ('nbmois', models.IntegerField(blank=True, db_column='Nbmois', null=True)),
                ('datefinstage', models.DateTimeField(blank=True, db_column='DateFinStage', null=True)),
                ('cinpdf', models.FileField(db_column='Cinpdf', upload_to='')),
                ('cvpdf', models.FileField(db_column='CVpdf', upload_to='')),
                ('demandepdf', models.FileField(db_column='Demandepdf', upload_to='')),
                ('assurancepdf', models.FileField(db_column='Assurancepdf', upload_to='')),
            ],
            options={
                'db_table': 'Stage',
                'managed': False,
            },
        ),
    ]
