# Generated by Django 4.0.4 on 2022-05-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAbsence', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concours',
        ),
        migrations.RemoveField(
            model_name='conjointpersonnel',
            name='idconjoint_field',
        ),
        migrations.DeleteModel(
            name='Diplome',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Echelle',
        ),
        migrations.DeleteModel(
            name='Echellon',
        ),
        migrations.DeleteModel(
            name='Enfant',
        ),
        migrations.DeleteModel(
            name='Fonction',
        ),
        migrations.DeleteModel(
            name='Fonctionpersonnel',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Gradepersonnel',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Servicepersonnel',
        ),
        migrations.DeleteModel(
            name='Conjoint',
        ),
        migrations.DeleteModel(
            name='Conjointpersonnel',
        ),
    ]
