# Generated by Django 4.0.4 on 2022-06-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avencement',
            fields=[
                ('iavencement', models.AutoField(db_column='IAvencement', primary_key=True, serialize=False)),
                ('dategrade', models.DateTimeField(blank=True, db_column='DateGrade', null=True)),
                ('changementdegrade', models.CharField(blank=True, db_collation='French_CI_AS', db_column='ChangementDeGrade', max_length=100, null=True)),
                ('indice', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Indice', max_length=15, null=True)),
                ('dateechellon', models.DateTimeField(blank=True, db_column='DateEchellon', null=True)),
                ('changementdechellon', models.CharField(blank=True, db_collation='French_CI_AS', db_column='ChangementDEchellon', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Avencement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notation',
            fields=[
                ('idnotation', models.AutoField(db_column='IdNotation', primary_key=True, serialize=False)),
                ('note', models.IntegerField(blank=True, db_column='Note', null=True)),
                ('annee', models.IntegerField(blank=True, db_column='Annee', null=True)),
            ],
            options={
                'db_table': 'Notation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rythme',
            fields=[
                ('idrythme', models.AutoField(db_column='IdRythme', primary_key=True, serialize=False)),
                ('rapide', models.IntegerField(blank=True, db_column='Rapide', null=True)),
                ('moyen', models.IntegerField(blank=True, db_column='Moyen', null=True)),
                ('lent', models.IntegerField(blank=True, db_column='Lent', null=True)),
            ],
            options={
                'db_table': 'Rythme',
                'managed': False,
            },
        ),
    ]
