# Generated by Django 4.0.4 on 2022-06-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAvancement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avencement',
            options={'managed': False, 'verbose_name': 'الترقية', 'verbose_name_plural': 'الترقيات'},
        ),
        migrations.AlterModelOptions(
            name='notation',
            options={'managed': False, 'verbose_name': 'النقطة', 'verbose_name_plural': 'النقط'},
        ),
        migrations.AlterModelOptions(
            name='rythme',
            options={'managed': False, 'verbose_name': 'النسق', 'verbose_name_plural': 'النسق'},
        ),
    ]
