# Generated by Django 4.0.4 on 2022-04-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('idconcours', models.AutoField(db_column='IdConcours', primary_key=True, serialize=False)),
                ('libelleconcoursar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleConcoursAr', max_length=30, null=True)),
                ('libelleconcoursfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleConcoursFr', max_length=30, null=True)),
                ('dateconcours', models.DateTimeField(blank=True, db_column='DateConcours', null=True)),
            ],
            options={
                'db_table': 'Concours',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conjoint',
            fields=[
                ('idconjoint', models.AutoField(db_column='IdConjoint', primary_key=True, serialize=False)),
                ('cin', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Cin', max_length=20, null=True)),
                ('nomar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NomAr', max_length=20, null=True)),
                ('nomfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NomFr', max_length=20, null=True)),
                ('prenomar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='PrenomAr', max_length=20, null=True)),
                ('prenomfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='PrenomFr', max_length=20, null=True)),
                ('datenaissance', models.DateTimeField(blank=True, db_column='DateNaissance', null=True)),
                ('lieunaissance', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LieuNaissance', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Conjoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Echelle',
            fields=[
                ('idechelle', models.AutoField(db_column='IdEchelle', primary_key=True, serialize=False)),
                ('echelle', models.IntegerField(blank=True, db_column='Echelle', null=True)),
                ('dateechelle', models.DateTimeField(blank=True, db_column='DateEchelle', null=True)),
            ],
            options={
                'db_table': 'Echelle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Echellon',
            fields=[
                ('idechellon', models.AutoField(db_column='IdEchellon', primary_key=True, serialize=False)),
                ('echellon', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Echellon', max_length=30, null=True)),
                ('dateechellon', models.DateTimeField(blank=True, db_column='DateEchellon', null=True)),
            ],
            options={
                'db_table': 'Echellon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('idfonction', models.AutoField(db_column='IdFonction', primary_key=True, serialize=False)),
                ('libellefontionar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleFontionAr', max_length=50, null=True)),
                ('libellefonctionfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleFonctionFr', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Fonction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('idgrade', models.AutoField(db_column='IdGrade', primary_key=True, serialize=False)),
                ('gradear', models.CharField(blank=True, db_collation='French_CI_AS', db_column='GradeAr', max_length=30, null=True)),
                ('gradefr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='GradeFr', max_length=30, null=True)),
                ('dategrade', models.DateTimeField(blank=True, db_column='DateGrade', null=True)),
            ],
            options={
                'db_table': 'Grade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('idpersonnel', models.AutoField(db_column='IdPersonnel', primary_key=True, serialize=False)),
                ('nomar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NomAr', max_length=20, null=True)),
                ('prenomar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='PrenomAr', max_length=20, null=True)),
                ('nomfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NomFr', max_length=20, null=True)),
                ('prenomfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='PrenomFr', max_length=20, null=True)),
                ('cin', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Cin', max_length=20, null=True)),
                ('datenaissance', models.DateTimeField(blank=True, db_column='DateNaissance', null=True)),
                ('lieunaissancear', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LieuNaissanceAr', max_length=30, null=True)),
                ('lieunaissancefr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LieuNaissanceFr', max_length=30, null=True)),
                ('adressear', models.CharField(blank=True, db_collation='French_CI_AS', db_column='AdresseAr', max_length=100, null=True)),
                ('adressefr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='AdresseFr', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Email', max_length=40, null=True)),
                ('tele', models.IntegerField(blank=True, db_column='Tele', null=True)),
                ('situationfamilialear', models.CharField(blank=True, db_collation='French_CI_AS', db_column='SituationFamilialeAr', max_length=40, null=True)),
                ('situationfamilialefr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='SituationFamilialeFr', max_length=40, null=True)),
                ('sexe', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Sexe', max_length=30, null=True)),
                ('vaccination', models.BooleanField(blank=True, db_column='Vaccination', null=True)),
                ('numerolocation', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NumeroLocation', max_length=60, null=True)),
                ('numerofinancier', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NumeroFinancier', max_length=60, null=True)),
                ('daterecrutement', models.DateTimeField(blank=True, db_column='DateRecrutement', null=True)),
                ('datedemarcation', models.DateTimeField(blank=True, db_column='DateDemarcation', null=True)),
                ('dateparrainageretraite', models.DateTimeField(blank=True, db_column='DateParrainageRetraite', null=True)),
                ('cmr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Cmr', max_length=60, null=True)),
                ('posteemploye', models.CharField(blank=True, db_collation='French_CI_AS', db_column='PosteEmploye', max_length=60, null=True)),
                ('metier', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Metier', max_length=60, null=True)),
                ('typeemploye', models.CharField(blank=True, db_collation='French_CI_AS', db_column='TypeEmploye', max_length=60, null=True)),
                ('tachesprecedentes', models.CharField(blank=True, db_collation='French_CI_AS', db_column='TachesPrecedentes', max_length=60, null=True)),
                ('rib', models.IntegerField(blank=True, db_column='Rib', null=True)),
                ('ancienneteadmi', models.CharField(blank=True, db_collation='French_CI_AS', db_column='ancienneteAdmi', max_length=50, null=True)),
                ('numcnopsaf', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NumCnopsAf', max_length=50, null=True)),
                ('numcnopsim', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NumCnopsIm', max_length=50, null=True)),
                ('administrationapp', models.CharField(blank=True, db_collation='French_CI_AS', db_column='AdministrationApp', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conjointpersonnel',
            fields=[
                ('idconjoint_field', models.OneToOneField(db_column='IdConjoint#', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='GestionPersonnel.conjoint')),
            ],
            options={
                'db_table': 'ConjointPersonnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fonctionpersonnel',
            fields=[
                ('idfonction_field', models.OneToOneField(db_column='IdFonction#', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='GestionPersonnel.fonction')),
                ('datefonction', models.DateTimeField(db_column='DateFonction')),
            ],
            options={
                'db_table': 'FonctionPersonnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gradepersonnel',
            fields=[
                ('idgrade_field', models.OneToOneField(db_column='IdGrade#', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='GestionPersonnel.grade')),
                ('dategrade', models.DateTimeField(blank=True, db_column='DateGrade', null=True)),
                ('changementdegrade', models.CharField(blank=True, db_collation='French_CI_AS', db_column='ChangementDeGrade', max_length=100, null=True)),
            ],
            options={
                'db_table': 'GradePersonnel',
                'managed': False,
            },
        ),
    ]
