# Generated by Django 4.0.4 on 2022-04-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0002_division_service_servicepersonnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('iddiplome', models.AutoField(db_column='IdDiplome', primary_key=True, serialize=False)),
                ('diplomefr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='DiplomeFr', max_length=40, null=True)),
                ('diplomear', models.CharField(blank=True, db_collation='French_CI_AS', db_column='DiplomeAr', max_length=40, null=True)),
                ('etablissement', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Etablissement', max_length=100, null=True)),
                ('specialitear', models.CharField(blank=True, db_collation='French_CI_AS', db_column='SpecialiteAr', max_length=100, null=True)),
                ('specialitefr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='SpecialiteFr', max_length=100, null=True)),
                ('datediplome', models.DateTimeField(blank=True, db_column='DateDiplome', null=True)),
            ],
            options={
                'db_table': 'Diplome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('idenfant', models.AutoField(db_column='IdEnfant', primary_key=True, serialize=False)),
                ('nomar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NomAr', max_length=20, null=True)),
                ('nomfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NomFr', max_length=20, null=True)),
                ('prenomar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='PrenomAr', max_length=20, null=True)),
                ('prenomfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='PrenomFr', max_length=20, null=True)),
                ('datenaissance', models.DateTimeField(blank=True, db_column='DateNaissance', null=True)),
                ('lieunaissancear', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LieuNaissanceAr', max_length=20, null=True)),
                ('lieunaissancefr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LieuNaissanceFr', max_length=20, null=True)),
                ('lienjuridique', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LienJuridique', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Enfant',
                'managed': False,
            },
        ),
    ]
