# Generated by Django 4.0.4 on 2022-05-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0003_diplome_enfant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('idindice', models.AutoField(db_column='IdIndice', primary_key=True, serialize=False)),
                ('indice', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Indice', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Indice',
                'managed': False,
            },
        ),
    ]
