# Generated by Django 4.0.4 on 2022-05-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0004_indice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gradeechellon',
            fields=[
                ('idgradeechellon', models.AutoField(db_column='IdGradeEchellon', primary_key=True, serialize=False)),
                ('indice', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Indice', max_length=15, null=True)),
                ('dateechellon', models.DateTimeField(blank=True, db_column='DateEchellon', null=True)),
                ('changementdechellon', models.CharField(blank=True, db_collation='French_CI_AS', db_column='ChangementDEchellon', max_length=100, null=True)),
            ],
            options={
                'db_table': 'GradeEchellon',
                'managed': False,
            },
        ),
    ]
