# Generated by Django 4.0.4 on 2022-05-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0006_statutgrade_delete_gradeechellon_delete_indice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annexe',
            fields=[
                ('idannexe', models.AutoField(db_column='IdAnnexe', primary_key=True, serialize=False)),
                ('libelleannexear', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleAnnexeAr', max_length=20, null=True)),
                ('libelleannexefr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleAnnexeFr', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Annexe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Annexepersonnel',
            fields=[
                ('idannexepersonnel', models.AutoField(db_column='IdAnnexePersonnel', primary_key=True, serialize=False)),
                ('dateaffectation', models.DateTimeField(blank=True, db_column='DateAffectation', null=True)),
            ],
            options={
                'db_table': 'AnnexePersonnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('iddistrict', models.AutoField(db_column='IdDistrict', primary_key=True, serialize=False)),
                ('libelledistrictar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleDistrictAr', max_length=100, null=True)),
                ('libelledistrictfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleDistrictFr', max_length=100, null=True)),
            ],
            options={
                'db_table': 'District',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('identite', models.AutoField(db_column='IdEntite', primary_key=True, serialize=False)),
                ('libelleentitenar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleEntitenAr', max_length=100, null=True)),
                ('libelleentitefr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleEntiteFr', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Entite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pashalik',
            fields=[
                ('idpashalik', models.AutoField(db_column='IdPashalik', primary_key=True, serialize=False)),
                ('libellepashalikar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibellePashalikAr', max_length=100, null=True)),
                ('libellepashalikfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibellePashalikFr', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Pashalik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pashalikpersonnel',
            fields=[
                ('idpashalikpersonnel', models.AutoField(db_column='IdPashalikPersonnel', primary_key=True, serialize=False)),
                ('dateaffectation', models.DateTimeField(blank=True, db_column='DateAffectation', null=True)),
            ],
            options={
                'db_table': 'PashalikPersonnel',
                'managed': False,
            },
        ),
    ]
