# Generated by Django 4.0.4 on 2022-05-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0007_annexe_annexepersonnel_district_entite_pashalik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caidat',
            fields=[
                ('idcaidat', models.AutoField(db_column='IdCaidat', primary_key=True, serialize=False)),
                ('libellecaidatar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleCaidatAr', max_length=20, null=True)),
                ('libellecaidatfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleCaidatFr', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Caidat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caidatpersonnel',
            fields=[
                ('idcaidatpersonnel', models.AutoField(db_column='IdCaidatPersonnel', primary_key=True, serialize=False)),
                ('dateaffectation', models.DateTimeField(blank=True, db_column='DateAffectation', null=True)),
            ],
            options={
                'db_table': 'CaidatPersonnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cercle',
            fields=[
                ('idcercle', models.AutoField(db_column='IdCercle', primary_key=True, serialize=False)),
                ('libellecerclear', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleCercleAr', max_length=100, null=True)),
                ('libellecerclefr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleCercleFr', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Cercle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParametrageRetraite',
            fields=[
                ('idparametrageretraite', models.AutoField(db_column='IdParametrageRetraite', primary_key=True, serialize=False)),
                ('nbannee', models.IntegerField(blank=True, db_column='NbAnnee', null=True)),
                ('nbmois', models.IntegerField(blank=True, db_column='NbMois', null=True)),
            ],
            options={
                'db_table': 'ParametrageRetraite',
                'managed': False,
            },
        ),
    ]
