# Generated by Django 4.0.4 on 2022-05-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0008_caidat_caidatpersonnel_cercle_parametrageretraite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reafectation',
            fields=[
                ('idreafectation', models.AutoField(db_column='IdReafectation', primary_key=True, serialize=False)),
                ('libellereafectationar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleReafectationAr', max_length=20, null=True)),
                ('libellereafectationfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleReafectationFr', max_length=20, null=True)),
                ('idorganismeparent', models.IntegerField(blank=True, db_column='IdOrganismeParent', null=True)),
                ('organisme', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Organisme', max_length=80, null=True)),
                ('datereafectation', models.DateTimeField(blank=True, db_column='DateReafectation', null=True)),
            ],
            options={
                'db_table': 'Reafectation',
                'managed': False,
            },
        ),
    ]
