# Generated by Django 4.0.4 on 2022-06-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0008_caidat_caidatpersonnel_cercle_parametrageretraite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reafectation',
            fields=[
                ('idreafectation', models.AutoField(db_column='IdReafectation', primary_key=True, serialize=False)),
                ('libellereafectationar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleReafectationAr', max_length=80, null=True)),
                ('libellereafectationfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleReafectationFr', max_length=80, null=True)),
                ('idorganismeparent', models.IntegerField(blank=True, db_column='IdOrganismeParent', null=True)),
                ('organisme', models.CharField(blank=True, db_collation='French_CI_AS', db_column='Organisme', max_length=80, null=True)),
                ('datereafectation', models.DateTimeField(blank=True, db_column='DateReafectation', null=True)),
            ],
            options={
                'db_table': 'Reafectation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idstatut', models.AutoField(db_column='IdStatut', primary_key=True, serialize=False)),
                ('libellestatutar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleStatutAr', max_length=100, null=True)),
                ('libellestatutfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleStatutFr', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Statut',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statutpersonnel',
            fields=[
                ('idstatutpersonnel', models.AutoField(db_column='IdStatutPersonnel', primary_key=True, serialize=False)),
                ('datestatut', models.DateTimeField(blank=True, db_column='DateStatut', null=True)),
            ],
            options={
                'db_table': 'StatutPersonnel',
                'managed': False,
            },
        ),
    ]
