# Generated by Django 4.0.4 on 2022-05-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0009_reafectation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idstatut', models.AutoField(db_column='IdStatut', primary_key=True, serialize=False)),
                ('libellestatutar', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleStatutAr', max_length=100, null=True)),
                ('libellestatutfr', models.CharField(blank=True, db_collation='French_CI_AS', db_column='LibelleStatutFr', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Statut',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statutpersonnel',
            fields=[
                ('idstatutpersonnel', models.AutoField(db_column='IdStatutPersonnel', primary_key=True, serialize=False)),
                ('datestatut', models.DateTimeField(blank=True, db_column='DateStatut', null=True)),
            ],
            options={
                'db_table': 'StatutPersonnel',
                'managed': False,
            },
        ),
    ]
