# Generated by Django 4.0.4 on 2022-06-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0009_reafectation_statut_statutpersonnel'),
        ('GestionPersonnel', '0010_statut_statutpersonnel'),
    ]

    operations = [
    ]
