# Generated by Django 4.0.4 on 2022-06-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0012_attestationtravail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attestationtravail',
        ),
    ]
