# Generated by Django 4.0.4 on 2022-06-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0014_attestationtravail'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuitterTerritoire',
            fields=[
                ('idquitterterritoire', models.AutoField(db_column='IdQuitterTerritoire', primary_key=True, serialize=False)),
                ('numquitterterritoire', models.IntegerField(blank=True, db_column='NumQuitterTerritoire', null=True)),
                ('datedelivre', models.DateTimeField(blank=True, db_column='DateDelivre', null=True)),
            ],
            options={
                'db_table': 'AttestationTravail',
                'managed': False,
            },
        ),
    ]
