# Generated by Django 4.0.4 on 2022-06-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0015_quitterterritoire'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quitterterritoire',
            table='QuitterTerritoire',
        ),
    ]
