# Generated by Django 4.0.4 on 2022-06-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonnel', '0016_alter_quitterterritoire_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annexe',
            options={'managed': False, 'verbose_name': 'الملحقة', 'verbose_name_plural': 'الملحقات'},
        ),
        migrations.AlterModelOptions(
            name='annexepersonnel',
            options={'managed': False, 'verbose_name': 'ملحقة الموظف', 'verbose_name_plural': 'ملحقة الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='attestationtravail',
            options={'managed': False, 'verbose_name': 'شهادة العمل', 'verbose_name_plural': 'شهادات العمل'},
        ),
        migrations.AlterModelOptions(
            name='caidat',
            options={'managed': False, 'verbose_name': 'القيادة', 'verbose_name_plural': 'القيادات'},
        ),
        migrations.AlterModelOptions(
            name='caidatpersonnel',
            options={'managed': False, 'verbose_name': 'قيادة الموظف', 'verbose_name_plural': 'قيادة الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='cercle',
            options={'managed': False, 'verbose_name': 'الدائرة', 'verbose_name_plural': 'الدائرات'},
        ),
        migrations.AlterModelOptions(
            name='concours',
            options={'managed': False, 'verbose_name': 'الإمتحان', 'verbose_name_plural': 'الإمتحانات'},
        ),
        migrations.AlterModelOptions(
            name='conjoint',
            options={'managed': False, 'verbose_name': 'الزوج', 'verbose_name_plural': 'الأزواج'},
        ),
        migrations.AlterModelOptions(
            name='conjointpersonnel',
            options={'managed': False, 'verbose_name': 'زوج الموظف', 'verbose_name_plural': 'زوج الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='diplome',
            options={'managed': False, 'verbose_name': 'الشهادة', 'verbose_name_plural': 'الشهادات'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'managed': False, 'verbose_name': 'المنطقة', 'verbose_name_plural': 'المنطقات'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'managed': False, 'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='echelle',
            options={'managed': False, 'verbose_name': 'السلم', 'verbose_name_plural': 'السلم'},
        ),
        migrations.AlterModelOptions(
            name='echellon',
            options={'managed': False, 'verbose_name': 'الرتبة', 'verbose_name_plural': 'الرتب'},
        ),
        migrations.AlterModelOptions(
            name='enfant',
            options={'managed': False, 'verbose_name': 'الطفل', 'verbose_name_plural': 'الأطفال'},
        ),
        migrations.AlterModelOptions(
            name='entite',
            options={'managed': False, 'verbose_name': 'الهيئة', 'verbose_name_plural': 'الهيئات'},
        ),
        migrations.AlterModelOptions(
            name='fonction',
            options={'managed': False, 'verbose_name': 'المهمة', 'verbose_name_plural': 'المهمات'},
        ),
        migrations.AlterModelOptions(
            name='fonctionpersonnel',
            options={'managed': False, 'verbose_name': 'مهمة الموظف', 'verbose_name_plural': 'مهمة الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'managed': False, 'verbose_name': 'الدرجة', 'verbose_name_plural': 'الدرجات'},
        ),
        migrations.AlterModelOptions(
            name='gradepersonnel',
            options={'managed': False, 'verbose_name': 'درجة الموظف', 'verbose_name_plural': 'درجة الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='parametrageretraite',
            options={'managed': False, 'verbose_name': 'عدد سنوات التقاعد', 'verbose_name_plural': 'عدد سنوات التقاعد'},
        ),
        migrations.AlterModelOptions(
            name='pashalik',
            options={'managed': False, 'verbose_name': 'الباشوية', 'verbose_name_plural': 'الباشاويات'},
        ),
        migrations.AlterModelOptions(
            name='pashalikpersonnel',
            options={'managed': False, 'verbose_name': 'باشوية الموظف', 'verbose_name_plural': 'باشوية الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'managed': False, 'verbose_name': 'الموظف', 'verbose_name_plural': 'الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='quitterterritoire',
            options={'managed': False, 'verbose_name': 'شهادة مغادرة التراب الوطني', 'verbose_name_plural': 'شهادات مغادرة التراب الوطني'},
        ),
        migrations.AlterModelOptions(
            name='reafectation',
            options={'managed': False, 'verbose_name': 'التعيين', 'verbose_name_plural': 'التعيينات'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False, 'verbose_name': 'المصلحة', 'verbose_name_plural': 'المصلحات'},
        ),
        migrations.AlterModelOptions(
            name='servicepersonnel',
            options={'managed': False, 'verbose_name': 'مصلحة الموظف', 'verbose_name_plural': 'مصلحة الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='statut',
            options={'managed': False, 'verbose_name': 'الحالة النضامية', 'verbose_name_plural': 'الحالات النضامية'},
        ),
        migrations.AlterModelOptions(
            name='statutgrade',
            options={'managed': False, 'verbose_name': 'حالة الدرجة', 'verbose_name_plural': 'حالة الدرجات'},
        ),
        migrations.AlterModelOptions(
            name='statutpersonnel',
            options={'managed': False, 'verbose_name': 'حالة الموظف', 'verbose_name_plural': 'حالة الموظفين'},
        ),
    ]
